(()=>{
'use strict';
const RELAYS=['wss://relay.damus.io','wss://nos.lol','wss://relay.snort.social'];
const STATE_KIND=30078,PRESENCE_KIND=20001;
const meals=[{id:'breakfast',name:'Breakfast',icon:'🍳',bg:'#fff0c9'},{id:'lunch',name:'Lunch',icon:'🥪',bg:'#dff3e7'},{id:'dinner',name:'Dinner',icon:'🍝',bg:'#ffe0d8'},{id:'snacks',name:'Snacks & drinks',icon:'🍎',bg:'#e8e2ff'}];
const $=id=>document.getElementById(id);const enc=new TextEncoder(),dec=new TextDecoder();
const deviceId=localStorage.stinkyDeviceId||(localStorage.stinkyDeviceId=crypto.randomUUID());
let viewerName=localStorage.stinkyViewerName||'',roomCode='',roomTag='',secretKey=null,pubkey='',aesKey=null;
let state=null,selectedDate=new Date(),activeMeal='breakfast',editing=null;
let sockets=new Map(),presence=new Map(),publishTimer=null,reconnectTimers=new Map();selectedDate.setHours(12,0,0,0);
const blankState=()=>({version:1,name:'Stinky',emoji:'🐶',days:{},updatedAt:0,updatedBy:''});
const normaliseCode=s=>String(s||'').toUpperCase().replace(/[^A-Z2-9]/g,'').replace(/[01OI]/g,'');
const formatCode=s=>normaliseCode(s).match(/.{1,4}/g)?.join('-')||'';
const randomCode=()=>{const a='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let s='';crypto.getRandomValues(new Uint8Array(12)).forEach(v=>s+=a[v%a.length]);return formatCode(s)};
const hex=b=>[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('');
const b64=b=>btoa(String.fromCharCode(...new Uint8Array(b))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
const unb64=s=>{s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';return Uint8Array.from(atob(s),c=>c.charCodeAt(0))};
const hash=async s=>new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(s)));
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dateKey=()=>`${selectedDate.getFullYear()}-${String(selectedDate.getMonth()+1).padStart(2,'0')}-${String(selectedDate.getDate()).padStart(2,'0')}`;
const day=()=>state.days[dateKey()]||(state.days[dateKey()]={breakfast:[],lunch:[],dinner:[],snacks:[]});
const cacheKey=()=>`stinkyState:${normaliseCode(roomCode)}`;
async function setupRoom(code){roomCode=formatCode(code);if(normaliseCode(roomCode).length<8)throw Error('Code is too short');secretKey=await hash('stinky-signing-v1:'+normaliseCode(roomCode));pubkey=NostrTools.getPublicKey(secretKey);roomTag=hex(await hash('stinky-room-v1:'+normaliseCode(roomCode))).slice(0,40);aesKey=await crypto.subtle.importKey('raw',await hash('stinky-encryption-v1:'+normaliseCode(roomCode)),{name:'AES-GCM'},false,['encrypt','decrypt'])}
async function encrypt(obj){const iv=crypto.getRandomValues(new Uint8Array(12));const data=await crypto.subtle.encrypt({name:'AES-GCM',iv},aesKey,enc.encode(JSON.stringify(obj)));return JSON.stringify({v:1,i:b64(iv),d:b64(data)})}
async function decrypt(content){const x=JSON.parse(content);const data=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(x.i)},aesKey,unb64(x.d));return JSON.parse(dec.decode(data))}
function signed(kind,content,tags=[]){return NostrTools.finalizeEvent({kind,created_at:Math.floor(Date.now()/1000),tags:[['d',roomTag],['t','stinky-checklist'],...tags],content},secretKey)}
function connectAll(){RELAYS.forEach(connectRelay)}
function connectRelay(url){if(sockets.get(url)?.readyState===WebSocket.OPEN||sockets.get(url)?.readyState===WebSocket.CONNECTING)return;let ws;try{ws=new WebSocket(url)}catch{return}sockets.set(url,ws);ws.onopen=()=>{clearTimeout(reconnectTimers.get(url));updateConnection();ws.send(JSON.stringify(['REQ','stinky-'+deviceId.slice(0,8),{kinds:[STATE_KIND,PRESENCE_KIND],authors:[pubkey],'#d':[roomTag],limit:100}]));sendPresence()};ws.onmessage=async e=>{let m;try{m=JSON.parse(e.data)}catch{return}if(m[0]!=='EVENT')return;const ev=m[2];if(!ev||ev.pubkey!==pubkey)return;try{if(NostrTools.verifyEvent&&!NostrTools.verifyEvent(ev))return;if(ev.kind===STATE_KIND){const incoming=await decrypt(ev.content);if(!incoming||!incoming.days)return;if(!state||Number(incoming.updatedAt)>Number(state.updatedAt)){state=incoming;localStorage.setItem(cacheKey(),JSON.stringify(state));render()}}else if(ev.kind===PRESENCE_KIND){const p=await decrypt(ev.content);if(p.deviceId)presence.set(p.deviceId,Date.now());updatePresence()}}catch{}};ws.onclose=()=>{updateConnection();const t=setTimeout(()=>connectRelay(url),2500+Math.random()*2500);reconnectTimers.set(url,t)};ws.onerror=()=>{try{ws.close()}catch{}}}
function openSockets(){return[...sockets.values()].filter(x=>x.readyState===WebSocket.OPEN)}
function publishEvent(ev){openSockets().forEach(ws=>{try{ws.send(JSON.stringify(['EVENT',ev]))}catch{}})}
async function publishState(){if(!state)return;try{publishEvent(signed(STATE_KIND,await encrypt(state),[['client','stinkys-checklist']]));localStorage.setItem(cacheKey(),JSON.stringify(state))}catch{toast('Saved on this phone — reconnecting')}}
async function sendPresence(){if(!aesKey)return;presence.set(deviceId,Date.now());try{publishEvent(signed(PRESENCE_KIND,await encrypt({deviceId,name:viewerName||'Another phone',at:Date.now()}),[['device',deviceId.slice(0,12)]]))}catch{}updatePresence()}
function updateConnection(){const n=openSockets().length;$('dot').classList.toggle('live',n>0);$('status').textContent=n>0?'Live and syncing':'Reconnecting…'}
function updatePresence(){const now=Date.now();presence.set(deviceId,now);for(const[id,t]of presence)if(now-t>35000)presence.delete(id);const n=Math.max(1,presence.size);$('phones').textContent=n===1?'1 phone':`${n} phones live`}
function mutate(fn){fn();state.updatedAt=Date.now();state.updatedBy=viewerName||'A phone';localStorage.setItem(cacheKey(),JSON.stringify(state));render();clearTimeout(publishTimer);publishTimer=setTimeout(publishState,120)}
function enterApp(){localStorage.stinkyRecentRoom=roomCode;location.hash='r='+encodeURIComponent(normaliseCode(roomCode));$('welcome').classList.add('hidden');$('app').classList.remove('hidden');const cached=localStorage.getItem(cacheKey());state=cached?JSON.parse(cached):blankState();render();connectAll();sendPresence()}
async function join(code){try{await setupRoom(code);enterApp()}catch{toast('That room code does not look right')}}
function renderDate(){const today=new Date();today.setHours(12,0,0,0);const diff=Math.round((selectedDate-today)/86400000);$('dateLabel').textContent=diff===0?'Today':diff===1?'Tomorrow':diff===-1?'Yesterday':selectedDate.toLocaleDateString('en-GB',{weekday:'long'});$('dateFull').textContent=selectedDate.toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'})}
function render(){if(!state)return;$('emoji').textContent=state.emoji||'🐶';$('title').textContent=`${state.name||'Stinky'}'s Checklist`;$('codeBtn').textContent=`Private code ${formatCode(roomCode)}`;renderDate();const d=day();let total=0,done=0;$('meals').innerHTML='';meals.forEach(m=>{const items=d[m.id]||[];total+=items.length;done+=items.filter(x=>x.done).length;const el=document.createElement('article');el.className='meal-card';el.innerHTML=`<div class="meal-head"><div class="meal-icon" style="background:${m.bg}">${m.icon}</div><div class="meal-title"><h3>${m.name}</h3><small>${items.filter(x=>x.done).length}/${items.length} completed</small></div><button class="add-mini" data-add="${m.id}">+ Add</button></div><div class="items">${items.length?items.map((x,i)=>`<div class="item ${x.done?'done':''}"><input class="tick" type="checkbox" ${x.done?'checked':''} data-tick="${m.id}:${i}" aria-label="Tick ${escape(x.text)}"><div><div class="item-name">${escape(x.text)}</div>${x.note?`<div class="item-note">${escape(x.note)}</div>`:''}${x.done&&x.by?`<div class="item-by">Ticked by ${escape(x.by)}</div>`:''}</div><button class="edit" data-edit="${m.id}:${i}">•••</button></div>`).join(''):`<div class="empty">Nothing added yet</div>`}</div>`;$('meals').appendChild(el)});const pct=total?Math.round(done/total*100):0;$('ring').style.setProperty('--p',pct);$('percent').textContent=pct+'%';if(!total){$('progressTitle').textContent='Nothing added yet';$('progressSub').textContent=`Add the first thing ${state.name||'Stinky'} needs today.`}else if(done===total){$('progressTitle').textContent='Everything is done!';$('progressSub').textContent='Lovely work — the whole day is checked off.'}else{$('progressTitle').textContent=`${done} of ${total} completed`;$('progressSub').textContent=`A gentle reminder for ${state.name||'Stinky'} — no pressure.`}bindItems()}
function bindItems(){document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>openAdd(b.dataset.add));document.querySelectorAll('[data-tick]').forEach(c=>c.onchange=()=>{const[m,i]=c.dataset.tick.split(':');const wasAll=allDone();mutate(()=>{const x=day()[m][+i];x.done=c.checked;x.by=c.checked?(viewerName||'the other phone'):'';x.doneAt=c.checked?Date.now():0});if(!wasAll&&allDone())celebrate()});document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openEdit(b.dataset.edit))}
function allDone(){const a=meals.flatMap(m=>day()[m.id]||[]);return a.length>0&&a.every(x=>x.done)}
function show(id){$(id).classList.remove('hidden')}function hide(id){$(id).classList.add('hidden')}
function openAdd(meal='breakfast'){activeMeal=meal;$('itemText').value='';$('itemNote').value='';renderChoices();show('addSheet');setTimeout(()=>$('itemText').focus(),100)}
function renderChoices(){$('mealChoices').innerHTML=meals.map(m=>`<button type="button" class="meal-choice ${m.id===activeMeal?'selected':''}" data-meal="${m.id}">${m.icon} ${m.name}</button>`).join('');document.querySelectorAll('[data-meal]').forEach(b=>b.onclick=()=>{activeMeal=b.dataset.meal;renderChoices()})}
function openEdit(token){const[m,i]=token.split(':');editing={meal:m,index:+i};const x=day()[m][+i];$('editText').value=x.text;$('editNote').value=x.note||'';show('editSheet')}
function toast(s){const t=$('toast');t.textContent=s;t.classList.add('show');clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove('show'),1900)}
function celebrate(){const c=$('confetti');c.innerHTML='';for(let i=0;i<28;i++){const x=document.createElement('i');x.textContent=['♥','●','★','✦'][i%4];x.style.left=Math.random()*100+'vw';x.style.animationDelay=Math.random()*.35+'s';x.style.fontSize=12+Math.random()*18+'px';x.style.color=['#ff8e70','#ffd36c','#67ad7f','#9e86e8'][i%4];c.appendChild(x)}setTimeout(()=>c.innerHTML='',2100)}
async function share(){const url=location.origin+location.pathname+'#r='+encodeURIComponent(normaliseCode(roomCode));const text=`Join ${state.name||'Stinky'}'s live meal checklist. Open this private link:`;try{if(navigator.share)await navigator.share({title:"Stinky's Checklist",text,url});else{await navigator.clipboard.writeText(url);toast('Private link copied')}}catch(e){if(e.name!=='AbortError')toast('Could not share the link')}}
$('createBtn').onclick=()=>join(randomCode());$('joinForm').onsubmit=e=>{e.preventDefault();join($('joinCode').value)};$('leaveBtn').onclick=()=>{if(confirm('Leave this checklist on this phone?')){location.hash='';location.reload()}};
$('prev').onclick=()=>{selectedDate.setDate(selectedDate.getDate()-1);render()};$('next').onclick=()=>{selectedDate.setDate(selectedDate.getDate()+1);render()};$('dateMain').onclick=()=>{$('datePicker').value=dateKey();$('datePicker').showPicker?.()};$('datePicker').onchange=()=>{const[y,m,d]=$('datePicker').value.split('-').map(Number);selectedDate=new Date(y,m-1,d,12);render()};
$('fab').onclick=()=>openAdd();$('settingsBtn').onclick=()=>{$('listName').value=state.name||'Stinky';$('listEmoji').value=state.emoji||'🐶';$('myName').value=viewerName;show('settingsSheet')};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>hide(b.dataset.close));document.querySelectorAll('.sheet-backdrop').forEach(x=>x.onclick=e=>{if(e.target===x)hide(x.id)});
$('addForm').onsubmit=e=>{e.preventDefault();const text=$('itemText').value.trim();if(!text)return;mutate(()=>day()[activeMeal].push({id:crypto.randomUUID(),text,note:$('itemNote').value.trim(),done:false,by:'',createdAt:Date.now()}));hide('addSheet');toast('Added to both phones')};document.querySelectorAll('.quick button').forEach(b=>b.onclick=()=>{$('itemText').value=b.textContent;$('itemText').focus()});
$('editForm').onsubmit=e=>{e.preventDefault();if(!editing)return;mutate(()=>{const x=day()[editing.meal][editing.index];x.text=$('editText').value.trim();x.note=$('editNote').value.trim()});hide('editSheet');toast('Updated on both phones')};$('deleteBtn').onclick=()=>{if(editing&&confirm('Delete this item?')){mutate(()=>day()[editing.meal].splice(editing.index,1));hide('editSheet')}};
$('settingsForm').onsubmit=e=>{e.preventDefault();viewerName=$('myName').value.trim();localStorage.stinkyViewerName=viewerName;mutate(()=>{state.name=$('listName').value.trim()||'Stinky';state.emoji=$('listEmoji').value});hide('settingsSheet');sendPresence();toast('Saved for both phones')};$('shareBtn').onclick=share;$('codeBtn').onclick=async()=>{try{await navigator.clipboard.writeText(formatCode(roomCode));toast('Private code copied')}catch{toast(formatCode(roomCode))}};
$('resetBtn').onclick=()=>{if(confirm('Untick everything for this day?'))mutate(()=>meals.forEach(m=>(day()[m.id]||[]).forEach(x=>{x.done=false;x.by='';x.doneAt=0})))};$('clearBtn').onclick=()=>{if(confirm('Remove every item for this day?'))mutate(()=>state.days[dateKey()]={breakfast:[],lunch:[],dinner:[],snacks:[]})};
window.addEventListener('online',connectAll);document.addEventListener('visibilitychange',()=>{if(!document.hidden){connectAll();sendPresence()}});setInterval(sendPresence,12000);setInterval(updatePresence,5000);
const fromHash=new URLSearchParams(location.hash.replace(/^#/,'')),code=fromHash.get('r'),recent=localStorage.stinkyRecentRoom;if(recent){$('recentBtn').classList.remove('hidden');$('recentBtn').textContent='Open recent checklist '+formatCode(recent);$('recentBtn').onclick=()=>join(recent)}if(code)join(code);
})();
